config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get 'import'
    end
    resources :variants
  end
  resources :accounts do
    member do
      get 'test_connection'
    end
  end
  get 'dashboard/index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	validates_presence_of :shopify_account_url
	validates_presence_of :shopify_api_key
	validates_presence_of :shopify_password
	validates_presence_of :shopify_shared_secret
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :variants
end

app/models/variant.rb
class Variant < ActiveRecord::Base
	belongs_to :product
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:shopify_account_url, :shopify_api_key, :shopify_password, :shopify_shared_secret)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :shopify_product_id, :last_shopify_sync)
    end

    # GET /products/import
    # GET /products/import.json
    def import
    # For now we'll use the first Account in the database
      account = Account.first
      # Instantiate the ShopifyIntegration class
      shopify_integration = ShopifyIntegration.new(
      api_key: account.shopify_api_key,
      shared_secret: account.shopify_shared_secret,
      url: account.shopify_account_url,
      password: account.shopify_password)
      respond_to do |format|
        shopify_integration.connect
        result = shopify_integration.import_products
        format.html { redirect_to ({action: :index}),
          notice: "#{result[:created].to_i} created,
          #{result[:updated]}
          updated, #{result[:failed]} failed." }
      end
    end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_product
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_variant
      @variant = @product.variants.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:product_id, :shopify_variant_id, :optiona1, :option2, :option3, :sku, :barcode, :price, :last_shopify_sync)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shopify_account_url %><br>
    <%= f.text_field :shopify_account_url %>
  </div>
  <div class="field">
    <%= f.label :shopify_api_key %><br>
    <%= f.text_field :shopify_api_key %>
  </div>
  <div class="field">
    <%= f.label :shopify_password %><br>
    <%= f.text_field :shopify_password %>
  </div>
  <div class="field">
    <%= f.label :shopify_shared_secret %><br>
    <%= f.text_field :shopify_shared_secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Shopify account url</th>
      <th>Shopify api key</th>
      <th>Shopify password</th>
      <th>Shopify shared secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.shopify_account_url %></td>
        <td><%= account.shopify_api_key %></td>
        <td><%= account.shopify_password %></td>
        <td><%= account.shopify_shared_secret %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shopify account url:</strong>
  <%= @account.shopify_account_url %>
</p>

<p>
  <strong>Shopify api key:</strong>
  <%= @account.shopify_api_key %>
</p>

<p>
  <strong>Shopify password:</strong>
  <%= @account.shopify_password %>
</p>

<p>
  <strong>Shopify shared secret:</strong>
  <%= @account.shopify_shared_secret %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

<%= link_to "Test Connection",
test_connection_account_path(@account), :class => 'btn' %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shopifydemo" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ContestApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Accounts", accounts_path%></li>
            <li><%= link_to "Products", products_path%></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_product_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_product_id) %>
  </div>
  <div class="form-group">
    <%= f.label :last_shopify_sync, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_shopify_sync, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_shopify_sync) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <p><a href="<%= import_products_path %>">Import Products</a></p>
</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:shopify_product_id) %></th>
      <th><%= model_class.human_attribute_name(:last_shopify_sync) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.shopify_product_id %></td>
        <td><%= product.last_shopify_sync %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_product_id) %>:</strong></dt>
  <dd><%= @product.shopify_product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_shopify_sync) %>:</strong></dt>
  <dd><%= @product.last_shopify_sync %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/variants/_form.html.erb
<%= form_for @variant, :html => { :class => "form-horizontal variant" } do |f| %>

  <% if @variant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @variant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>
  <div class="form-group">
    <%= f.label :shopify_variant_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopify_variant_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopify_variant_id) %>
  </div>
  <div class="form-group">
    <%= f.label :optiona1, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :optiona1, :class => 'form-control' %>
    </div>
    <%=f.error_span(:optiona1) %>
  </div>
  <div class="form-group">
    <%= f.label :option2, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :option2, :class => 'form-control' %>
    </div>
    <%=f.error_span(:option2) %>
  </div>
  <div class="form-group">
    <%= f.label :option3, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :option3, :class => 'form-control' %>
    </div>
    <%=f.error_span(:option3) %>
  </div>
  <div class="form-group">
    <%= f.label :sku, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sku, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sku) %>
  </div>
  <div class="form-group">
    <%= f.label :barcode, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :barcode, :class => 'form-control' %>
    </div>
    <%=f.error_span(:barcode) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :last_shopify_sync, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_shopify_sync, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_shopify_sync) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                variants_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/variants/edit.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/variants/index.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:shopify_variant_id) %></th>
      <th><%= model_class.human_attribute_name(:optiona1) %></th>
      <th><%= model_class.human_attribute_name(:option2) %></th>
      <th><%= model_class.human_attribute_name(:option3) %></th>
      <th><%= model_class.human_attribute_name(:sku) %></th>
      <th><%= model_class.human_attribute_name(:barcode) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:last_shopify_sync) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= link_to variant.id, variant_path(variant) %></td>
        <td><%= variant.product_id %></td>
        <td><%= variant.shopify_variant_id %></td>
        <td><%= variant.optiona1 %></td>
        <td><%= variant.option2 %></td>
        <td><%= variant.option3 %></td>
        <td><%= variant.sku %></td>
        <td><%= variant.barcode %></td>
        <td><%= variant.price %></td>
        <td><%= variant.last_shopify_sync %></td>
        <td><%=l variant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_variant_path(variant), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      variant_path(variant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_variant_path,
            :class => 'btn btn-primary' %>

app/views/variants/new.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/variants/show.html.erb
<%- model_class = Variant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @variant.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shopify_variant_id) %>:</strong></dt>
  <dd><%= @variant.shopify_variant_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:optiona1) %>:</strong></dt>
  <dd><%= @variant.optiona1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:option2) %>:</strong></dt>
  <dd><%= @variant.option2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:option3) %>:</strong></dt>
  <dd><%= @variant.option3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sku) %>:</strong></dt>
  <dd><%= @variant.sku %></dd>
  <dt><strong><%= model_class.human_attribute_name(:barcode) %>:</strong></dt>
  <dd><%= @variant.barcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @variant.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_shopify_sync) %>:</strong></dt>
  <dd><%= @variant.last_shopify_sync %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              variants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_variant_path(@variant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              variant_path(@variant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>